# Render.com Blueprint for SE Gateway PHP Sender
# This file defines the infrastructure for automatic deployment
# Now with SMTP Persistence - No SMTP environment variables needed!

services:
  # Backend Service - Node.js API
  - type: web
    name: se-gateway-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: node backend/server/app.js
    healthCheckPath: /
    # Persistent disk for SMTP config storage (OPTIONAL - for 100% persistence)
    # Uncomment for paid plan to guarantee SMTP configs never reset:
    # disk:
    #   name: smtp-storage
    #   mountPath: /opt/render/project/src/backend/data
    #   sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DEBUG
        value: false
      # SMTP Config is now handled via frontend + file persistence
      # No SMTP environment variables needed!
      - key: ALLOWED_ORIGINS
        sync: false  # Set this in Render dashboard to your frontend URL

  # Frontend Service - PHP Web Application
  - type: web
    name: se-gateway-frontend
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: BACKEND_URL
        fromService:
          type: web
          name: se-gateway-backend
          property: host
      - key: PHP_ENV
        value: production
      - key: BACKEND_INTERNAL_URL
        value: http://se-gateway-backend:10000

# Auto-deploy on push to main branch
branches:
  - main
  - master

# Notes:
# 1. SMTP Configuration: Configure via app frontend (no env vars needed!)
# 2. ALLOWED_ORIGINS: Set in Render dashboard after deployment
# 3. Persistent Disk (Optional): Uncomment disk section for 100% guaranteed persistence
# 4. Free Tier: SMTP configs persist across most restarts (good for testing)
# 5. Paid Tier + Disk: SMTP configs NEVER reset (recommended for production)
