services:
  # Combined Service - PHP Frontend + Node.js Backend
  - type: web
    name: se-gateway
    runtime: docker
    region: oregon
    plan: starter  # $25/month - 2GB RAM, 1 vCPU, no spin-down
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PHP_ENV
        value: production
      - key: DEBUG
        value: false
      - key: PORT
        value: 10000

# Persistent disk for guaranteed SMTP config persistence (optional but recommended)
# Uncomment below to add persistent storage ($0.25/GB/month)
#disks:
#  - name: smtp-data
#    mountPath: /var/www/html/backend/data
#    sizeGB: 1
