services:
  # Combined Service - PHP Frontend + Node.js Backend
  - type: web
    name: se-gateway
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PHP_ENV
        value: production
      - key: DEBUG
        value: false
      - key: PORT
        value: 10000
